### ISSUE TITLE
 doubt

### ISSUE THREAD

**Issue by luiz123o** [dev-javascript/react-dyn-tabs#1]
Hello good morning my name is luiz I'm dev junior, I found your lib very good congratulations, I have a doubt I was using it in a project where each tab goes without a new specific form being created dynamically, through new tabs, but when rendering when I was typing in the input, the lib blocked this rendering, input n showing nothing can you give me a light?

**Comment by luiz123o** [comment]
> Hello good morning my name is luiz I'm dev junior, I found your lib very good congratulations, I have a doubt I was using it in a project where each tab goes without a new specific form being created dynamically, through new tabs, but when rendering when I was typing in the input, the lib blocked this rendering, input n showing nothing can you give me a light?

**Comment by dev-javascript** [comment]
Hi good morning, thank you, I'm happy this lib is useful for you.
I don't understand what you mean exactly, is your input element inside the panel component?
Do you mean something like this?
> const SimplePanelComponent= (props) => {
       const [value, setValue] = React.useState("");
       const onChange = (e) => {    setValue(e.target.value);  };
       return `<form><input type="text" onChange={onChange} value={value}> </input></form>`;
};

> const openNewTab: () => {
      instance.open({ title : "new tab", panelComponent : SimplePanelComponent });
    };

can you post your code and what you have tried?

**Comment by dev-javascript** [comment]
Hi good morning, thank you, i'm happy this lib is useful for you.
I have responded to your question

‫‪Luiz Otavio‬‏ ***@***.***‬‏> در تاریخ سه‌شنبه ۳ اوت ۲۰۲۱
ساعت ۱۸:۳۰ نوشت:‬

**Comment by luiz123o** [comment]
> Oi bom dia, obrigado, estou feliz que esta liberdade seja útil para você.
> Eu não entendo o que você quer dizer exatamente, é o seu elemento de entrada dentro do componente do painel?
> Você quer dizer algo assim?
> 
> > const SimplePanelComponent= (adereços) =>  { const [valor, setValue] = React.useState(");  const onChange = (e) => { setValue(e.target.value); };  retorno `<form><input type="text" onChange={onChange} value={value}> </input></form>`;
> > };
> 
> > const openNewTab: () =>  { instance.open({ title : "new tab", panelComponent : SimplePanelComponent });
> > };
> 
> você pode postar seu código e o que você tentou?
exactly that, the state of the component passed by the panelComponent when being updated was not rendered to screen

**Comment by dev-javascript** [comment]
Which version of react-dyn-tabs do you have?
The above code should work correctly.
Please can you show the specific piece of your code

**Comment by luiz123o** [comment]
![image](https://user-images.githubusercontent.com/43886036/128736964-74c4e4bb-6a48-440d-a1a2-4fa659ee91ac.png)

**Comment by dev-javascript** [comment]
It is really hard to guess but I think your input element is recreated every time and it is probably related to your form component.
For example : if inside your render method, a new function component is created every time by a higher-order component (React HOC), input element is not updated, but is re-created.
You can memoize your panel component, hopefully it will help you.

```
  const MemoizedPanel = React.memo(
    (props) => {
        return <YourPanelComponent {...props} />;
    },
    () => true
  );
  export default MemoizedPanel;
```
